[package]
name = "solproxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = "0.9"
tonic-reflection = "0.9"
prost = "0.11"
tokio = { version = "1.0", features = ["full"] }

[build-dependencies]
tonic-build = "0.9"


